### ISSUE TITLE
Problems in OSX: Exception in thread "main" java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by mjlassila** [jiemakel/las#4]
Latest release doesn't seem to work in OSX (El Capitan 10.11.6) using Java 1.8.0_05-b13. Is there some specific requirements for Java or operating system version? Previous LAS (v1.5.9) works fine. Also, the latest release works in interactive mode, but when given files to process the following error is thrown:

```
Exception in thread "main" java.lang.UnsupportedOperationException
	at java.util.AbstractList.set(AbstractList.java:132)
	at java.util.AbstractList$ListItr.set(AbstractList.java:426)
	at java.util.Collections.sort(Collections.java:234)
	at fi.seco.lexical.combined.CombinedLexicalAnalysisService.analyze(CombinedLexicalAnalysisService.java:572)
	at fi.seco.lexical.combined.CombinedLexicalAnalysisService.baseform(CombinedLexicalAnalysisService.java:266)
	at fi.seco.lexical.combined.CombinedLexicalAnalysisService.baseform(CombinedLexicalAnalysisService.java:261)
	at fi.seco.lexical.CompoundLexicalAnalysisService.baseform(CompoundLexicalAnalysisService.java:40)
	at LASCommandLineTool$.lemmatize(LASCommandLineTool.scala:291)
	at LASCommandLineTool$.$anonfun$main$8(LASCommandLineTool.scala:152)
	at LASCommandLineTool$.$anonfun$main$8$adapted(LASCommandLineTool.scala:151)
	at LASCommandLineTool$$$Lambda$90/1800031768.apply(Unknown Source)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
	at LASCommandLineTool$.$anonfun$main$7(LASCommandLineTool.scala:151)
	at LASCommandLineTool$.$anonfun$main$7$adapted(LASCommandLineTool.scala:142)
	at LASCommandLineTool$$$Lambda$86/339099861.apply(Unknown Source)
	at scala.collection.immutable.Stream.foreach(Stream.scala:530)
	at LASCommandLineTool$.$anonfun$main$6(LASCommandLineTool.scala:142)
	at LASCommandLineTool$.$anonfun$main$6$adapted(LASCommandLineTool.scala:142)
	at LASCommandLineTool$$$Lambda$82/240166646.apply(Unknown Source)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at LASCommandLineTool$.main(LASCommandLineTool.scala:142)
	at LASCommandLineTool.main(LASCommandLineTool.scala)

```

**Comment by jiemakel** [comment]
I'm unable to reproduce this on my OSX Sierra 10.12.6, Java 1.8.0_152. 

Can you provide me with a concrete test case, i.e. a combination of 1) LAS version (and flavour now that there are multiple) 2) command line parameters and 3) files that trigger the behaviour? 

The stack trace is quite strange, but I still have a hypothesis of what may be causing this.

**Comment by mjlassila** [comment]
This is las-fi, version 1.5.14.

```
./las-fi lemmatize /Users/matti/Downloads/amk/text/*.txt
```
Sample of problematic files (in total I have 49 files, approx 200KB each)
https://www.dropbox.com/s/rvz4356x0v9vxzb/corpus-sample.zip?dl=1

**Comment by jiemakel** [comment]
Still couldn't reproduce, so maybe there really is something wonky in your Java version. Could you retry with a different version?

The stack trace says that it's crashing while sorting a list due to the list in question not implementing the set method. Looking at the code around this, the list in question can either be a singleton or an arraylist. My hypothesis is that the singleton doesn't implement the set method, but on the other hand, it shouldn't need to, as the list wth a single entry is already naturally in the correct order.
